Introducing okta cli
oktadeveloper/okta-blog pull request #434
Opened 2020-10-04 21:05 UTC by dogeared

This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A title that's approved by Dev Marketing
- [ ] A URL that's approved by Dev Marketing
- [X] Rendered locally and confirmed that no Markdown typos exist

2020-10-05 14:13 UTC, bdemers commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +```bash
```suggestion
```txt
```

2020-10-05 14:14 UTC, bdemers commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +I put in some minimal information: name, email and company. In about 20 seconds, a shiny new Okta org is allocated for me and the Okta CLI shows me my Org URL (https://dev-159750.okta.com).
```suggestion
I put in some minimal information: name, email and company. In about 20 seconds, a shiny new Okta org is allocated for me and the Okta CLI shows me my Org URL (`https://dev-159750.okta.com`).
```

2020-10-05 14:15 UTC, bdemers commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +> **NOTE:** The order-of-operations here is not important. You can set your password before you choose a sample or afterwards. But, you should set your password in a timely fashion as that unique URL
Good call out!

2020-10-05 14:16 UTC, bdemers commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +Next, I see a list of available samples. As of this writing, there are four samples, but we are expanding that list. And, the Okta CLI automatically makes any new samples available in the list. You c
As man examples as you like, as long at it's <=5...

2020-10-05 14:17 UTC, bdemers commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +Finally, I see information about the Application that was provisioned in my Okta Org along with instructions to run the sample app.
```suggestion
Finally, I see information about the OIDC Application that was provisioned in my Okta Org along with instructions to run the sample app.
```

2020-10-05 14:20 UTC, bdemers commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +
Maybe mention a private/incognito window, to make it more obvious the user has logged in.

2020-10-05 14:21 UTC, bdemers commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +I don't know much at all about .NET programming. I couldn't tell you the difference between .NET Core and ASP.NET or the differences between 3 and 4 (I think there's a 5 coming?) But, in less than 5
This is a great statement!

2020-10-05 14:23 UTC, bdemers commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +1. Add the `OKTA_CLI_` placeholder values to the configuration files that make sense for your language and framework
```suggestion
1. Add the `OKTA_CLI_*` placeholder values to the configuration files that make sense for your language and framework
```

2020-10-05 14:24 UTC, bdemers approved these changes
A few minor nits

2020-10-05 14:24 UTC, bdemers commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +tags: [security, oauth, oauth2, oidc, openid-connect]
```suggestion
tags: [security, oauth, oauth2, oidc, openid-connect, cli]
```

2020-12-02 17:59 UTC, mraible commented
@dogeared Do you still plan on publishing this at some point? If so, we should get it scheduled!

2020-12-08 21:02 UTC, mraible requested changes
We might want to add a section with videos since we'll have three when this is published (Spring Boot, Angular, and React Native). Maybe a row with all three thumbnails? I can help with this.

2020-12-08 21:02 UTC, mraible commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +> The easiest way to see what configuration you need for your language and framework is to visit the official samples found in the [okta-samples](https://github.com/okta-samples) GitHub org.
"official" samples or "community" samples? 🙂

2020-12-08 21:02 UTC, mraible commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +| CLI_OKTA_CLIENT_ID     | The client id set by Okta for [web](https://developer.okta.com/docs/guides/implement-auth-code/overview/), [native](https://developer.okta.com/docs/guides/implement-auth-co
```suggestion
| CLI_OKTA_CLIENT_ID     | The client ID set by Okta for [web](https://developer.okta.com/docs/guides/implement-auth-code/overview/), [native](https://developer.okta.com/docs/guides/implement-auth-code-pkce/overview/), [browser](https://developer.okta.com/docs/guides/implement-auth-code-pkce/overview/) and [service](https://developer.okta.com/docs/guides/implement-client-creds/overview/) type apps                                 |
```

2020-12-08 21:02 UTC, mraible commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +
Is this table viewable on mobile?

2020-12-08 21:02 UTC, mraible commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +## Adding Samples for Okta CLI
Unfortunately, it's probably best to remove this section. Unless you want to offer an OktaDev t-shirt for creating a PR.

2020-12-08 21:02 UTC, mraible commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +## Wrapping Up
```suggestion
## Learn More About Okta, OAuth 2.0, and OpenID Connect
```

2020-12-09 18:07 UTC, dogeared commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +    "devops"
It's aspirational - I want to create samples for all of these. Would you suggest I remove some?

2020-12-09 18:11 UTC, dogeared commented on _source/_posts/2020-10-04-introducing-okta-cli.md
> +- "Add an Okta integration for your custom app in less than 5 minutes with the Okta CLI"
not at this time, but that would be a great flag. Kind of like anyone can host start.spring.io. <- @bdemers

2020-12-09 20:01 UTC, dogeared reviewed
I addressed all the feedback, rebased master and renamed the file for tomorrow. The tables look reasonable on mobile.

![image](https://user-images.githubusercontent.com/364562/101680936-665a4d00-3a2f-11eb-92ba-8c434e3aaa76.png)

![image](https://user-images.githubusercontent.com/364562/101680961-6e19f180-3a2f-11eb-99e3-fd922e6059fc.png)

2020-12-09 20:02 UTC, dogeared commented
I addressed all the feedback, rebased master and renamed the file for tomorrow. The tables look reasonable on mobile.

![image](https://user-images.githubusercontent.com/364562/101680936-665a4d00-3a2f-11eb-92ba-8c434e3aaa76.png)

![image](https://user-images.githubusercontent.com/364562/101680961-6e19f180-3a2f-11eb-99e3-fd922e6059fc.png)

2020-12-09 20:13 UTC, mraible commented
Nice! You might want to copy it into GDoc for editorial or ask @KMDeMat to review this PR and add comments inline.

2020-12-10 05:04 UTC, mraible approved these changes

2020-12-10 05:06 UTC, mraible commented
@dogeared I added screencasts in [this commit](https://github.com/oktadeveloper/okta-blog/pull/434/commits/22a82b4965d157fbaf517e557da3c1fae4fb0269). @Quorralyne I also added a link to your .NET 5 post. Please let us know if you'd rather have it link to a video (or update this branch with changes).

2020-12-10 05:08 UTC, mraible commented on _source/_posts/2020-12-10-introducing-okta-cli.md
> +## Get Started in Under 5 Minutes
I think it looks better as a number in the title. :)

2020-12-10 17:00 UTC, merged