updates to java-websockets for screencast
oktadeveloper/okta-blog pull request #495
Opened 2020-12-10 21:23 UTC by indiepopart

Updates to the post https://developer.okta.com/blog/2019/10/09/java-spring-websocket-tutorial
This updates are for recording the screencast.

2020-12-10 21:37 UTC, mraible commented
Thanks Jimena!

Can you please create a changelog in this post to point to this PR to let people know the post has been updated. You can see an example at the bottom of this post:

https://developer.okta.com/blog/2018/07/19/simple-crud-react-and-spring-boot

You can probably copy/paste the Markdown from this post and use it in yours.

> On Dec 10, 2020, at 2:23 PM, Jimena Garbarino <notifications@github.com> wrote:
> 
> ﻿
> Updates to the post https://developer.okta.com/blog/2019/10/09/java-spring-websocket-tutorial
> This updates are for recording the screencast.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/oktadeveloper/okta-blog/pull/495
> 
> Commit Summary
> 
> updates to java-websockets for screencast
> File Changes
> 
> M _source/_posts/2019-10-09-java-spring-websocket-tutorial.md (54)
> Patch Links:
> 
> https://github.com/oktadeveloper/okta-blog/pull/495.patch
> https://github.com/oktadeveloper/okta-blog/pull/495.diff
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-16 20:26 UTC, indiepopart commented
@mraible Shall I create a pull request for the code repository at https://github.com/oktadeveloper/okta-java-websockets-example?

2020-12-16 20:27 UTC, mraible commented
Yes, please do.

> On Dec 16, 2020, at 1:26 PM, Jimena Garbarino <notifications@github.com> wrote:
> 
> 
> @mraible <https://github.com/mraible> Shall I create a pull request for the code repository at https://github.com/oktadeveloper/okta-java-websockets-example <https://github.com/oktadeveloper/okta-java-websockets-example>?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/oktadeveloper/okta-blog/pull/495#issuecomment-746959853>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAAELZCJAFSNLMVGO6VDJRDSVEJXNANCNFSM4UVT6JPA>.
>

2020-12-17 21:25 UTC, indiepopart commented
Added change log. Not sure about the date. Created pull request https://github.com/oktadeveloper/okta-java-websockets-example/pull/2

2020-12-23 23:22 UTC, mraible requested changes
Thank you @indiepopart! Please add links in the changelog as suggested.

2020-12-23 23:22 UTC, mraible commented on _source/_posts/2019-10-09-java-spring-websocket-tutorial.md
> +* Dic 17, 2020: Update spring-boot version in curl line, to 2.4.0. Update Okta javascript SDK static link in index.html, to version to 4.0.0. Update Tone.js library link. Update the javascript authen
```suggestion
* Dec 23, 2020: Updated Spring Boot to version 2.4.0. Updated Okta Auth JS to version 4.0.0. Update Tone.js library link. See the code changes in the [example app on GitHub](https://github.com/oktadeveloper/okta-java-websockets-example/pull/2). Changes to this post can be viewed in [oktadeveloper/okta-blog#495](https://github.com/oktadeveloper/okta-blog/pull/495).
```

2020-12-23 23:22 UTC, mraible commented on _source/_posts/2019-10-09-java-spring-websocket-tutorial.md
> +**Changelog:**
```suggestion
<a name="changelog"></a>
**Changelog:**
```

2020-12-31 04:51 UTC, indiepopart commented
@mraible Links added!

2020-12-31 18:22 UTC, mraible approved these changes

2020-12-31 18:22 UTC, merged